### ISSUE TITLE
Erreur sur install kstars sur debian X86 64 bookworm fraichement installée.

### ISSUE THREAD

**Issue by dgedgedge** [Patrick-81/NAFABox#26]
Kstar-ekos-indi 

```
_ _| _ __   ___ | |_  __ _ | || | | | __ ___ | |_  __ _  _ __  ___     _   
 | | | '_ \ / __|| __|/ _` || || | | |/ // __|| __|/ _` || '__|/ __|  _| |_ 
 | | | | | |\__ \| |_| (_| || || | |   < \__ \| |_| (_| || |   \__ \ |_   _|
|___||_| |_||___/ \__|\__,_||_||_| |_|\_\|___/ \__|\__,_||_|   |___/   |_|  
                                                                            
 ___             _  _ 
|_ _| _ __    __| |(_)
 | | | '_ \  / _` || |
 | | | | | || (_| || |
|___||_| |_| \__,_||_|
                      
sudo: ppa-purge : commande introuvable
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/apt-add-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'
Atteint :1 http://deb.debian.org/debian bookworm InRelease
Atteint :2 http://security.debian.org/debian-security bookworm-security InRelease
Atteint :3 http://deb.debian.org/debian bookworm-updates InRelease
Lecture des listes de paquets…
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
E: Impossible de trouver le paquet kstars-bleeding
E: Impossible de trouver le paquet kstars-bleeding-dbg
E: Impossible de trouver le paquet gsc
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
E: Impossible de trouver le paquet indi-full
E: Impossible de trouver le paquet indi-dbg
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
xplanet est déjà la version la plus récente (1.3.1-3+b1).
xplanet-images est déjà la version la plus récente (1.3.1-3).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
astrometry.net est déjà la version la plus récente (0.93+dfsg-1+b1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.

(yad:10913): Gdk-CRITICAL **: 14:48:29.516: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed

(yad:10913): Gdk-CRITICAL **: 14:48:29.554: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
```

**Comment by dgedgedge** [comment]
Please have a look to : 

https://linuxhint.com/apt-add-repository-command-not-found-debian/

**Comment by dgedgedge** [comment]
Désolé je n'avais pas bien lu la doc.
=> Scripts non compatibles avec Debian.... Mais avec Ubuntu....

=> issue à fermer....

**Comment by dragonlost** [comment]
Effectivement les scripts ne sont pas compatible avec Debian. Pour les utiliser il faut suivre le tuto et passer par un ubuntu
